# Generated by Django 4.1.3 on 2022-11-23 02:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymclasses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymclass',
            name='last_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 23, 2, 2, 31, 525981, tzinfo=datetime.timezone.utc)),
        ),
    ]
