# Generated by Django 4.1.2 on 2022-12-08 23:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymclasses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymclass',
            name='last_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 7, 23, 40, 12, 713404, tzinfo=datetime.timezone.utc)),
        ),
    ]
