# Generated by Django 4.1.3 on 2022-11-23 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymclasses', '0002_alter_gymclass_last_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymclass',
            name='last_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 23, 17, 29, 29, 123388, tzinfo=datetime.timezone.utc)),
        ),
    ]
