# Generated by Django 4.1.2 on 2022-12-09 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymclasses', '0003_alter_gymclass_last_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymclass',
            name='last_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 8, 2, 10, 43, 56616, tzinfo=datetime.timezone.utc)),
        ),
    ]
