export const BASEURL = "http://127.0.0.1:8000/"
export const BASEURLNOEND = "http://127.0.0.1:8000"

export const LOCALE = 'en-CA'

export let PREVIOUSSTATE = null

export const GOOGLEAPIKEY = "AIzaSyBAxC5ZT5iHdhgBG5hvXg0axLWIJ4UfM_A"


export const LIPSUM = ("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Faucibus a pellentesque sit amet. Integer feugiat scelerisque varius morbi enim nunc faucibus a. Eget est lorem ipsum dolor sit amet consectetur adipiscing. Bibendum enim facilisis gravida neque convallis a cras semper. Morbi tristique senectus et netus et malesuada fames ac turpis. Aliquet nibh praesent tristique magna sit amet purus gravida quis. Vel pretium lectus quam id leo in. Pellentesque adipiscing commodo elit at imperdiet dui accumsan sit amet. Purus gravida quis blandit turpis. Elit sed vulputate mi sit amet. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Purus sit amet volutpat consequat mauris nunc congue. Viverra suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Nunc sed blandit libero volutpat. Donec ultrices tincidunt arcu non. Vitae elementum curabitur vitae nunc sed velit dignissim sodales ut.\n" +
    "Facilisis mauris sit amet massa vitae tortor condimentum. Etiam non quam lacus suspendisse faucibus. Feugiat nisl pretium fusce id velit ut tortor pretium viverra. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. At elementum eu facilisis sed odio. Eget nunc scelerisque viverra mauris in aliquam sem. At quis risus sed vulputate odio ut enim blandit volutpat. Orci phasellus egestas tellus rutrum tellus pellentesque. Amet mattis vulputate enim nulla aliquet porttitor lacus. Elementum sagittis vitae et leo. Cursus risus at ultrices mi tempus imperdiet nulla malesuada pellentesque. Lacinia quis vel eros donec ac odio tempor. Vitae elementum curabitur vitae nunc sed velit dignissim sodales ut. Molestie nunc non blandit massa enim. Nisl pretium fusce id velit ut. Magna etiam tempor orci eu lobortis elementum nibh tellus. Suscipit tellus mauris a diam maecenas sed enim. Consectetur lorem donec massa sapien faucibus. Quis lectus nulla at volutpat diam ut venenatis tellus in. Turpis egestas sed tempus urna et pharetra pharetra.\n" +
    "Sit amet consectetur adipiscing elit. Vitae purus faucibus ornare suspendisse sed nisi lacus sed. Mauris a diam maecenas sed enim ut sem viverra aliquet. Laoreet id donec ultrices tincidunt arcu non sodales neque sodales. Habitant morbi tristique senectus et netus et. A diam sollicitudin tempor id. Dui vivamus arcu felis bibendum ut tristique et. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Et sollicitudin ac orci phasellus egestas tellus rutrum tellus. Scelerisque varius morbi enim nunc faucibus a pellentesque sit amet. Pharetra magna ac placerat vestibulum lectus. Sit amet porttitor eget dolor morbi non arcu. Eget nullam non nisi est sit amet facilisis. Semper eget duis at tellus. Cursus risus at ultrices mi tempus imperdiet. Sit amet venenatis urna cursus eget nunc scelerisque viverra mauris.\n" +
    "Lobortis mattis aliquam faucibus purus in massa tempor. Sed egestas egestas fringilla phasellus. Scelerisque purus semper eget duis at tellus at urna condimentum. Scelerisque varius morbi enim nunc faucibus a. Justo nec ultrices dui sapien eget mi. Fusce id velit ut tortor pretium. Ridiculus mus mauris vitae ultricies leo integer. Blandit turpis cursus in hac. Ultrices in iaculis nunc sed augue. Tortor consequat id porta nibh venenatis. In hendrerit gravida rutrum quisque non tellus orci. Sed odio morbi quis commodo odio. Risus viverra adipiscing at in tellus integer.\n" +
    "Vehicula ipsum a arcu cursus. Nec feugiat nisl pretium fusce id velit ut tortor pretium. Consectetur libero id faucibus nisl tincidunt. Et tortor at risus viverra. Massa ultricies mi quis hendrerit dolor magna eget est. Sed faucibus turpis in eu mi bibendum neque. Tempus iaculis urna id volutpat lacus laoreet. Consectetur adipiscing elit ut aliquam purus sit amet. Velit laoreet id donec ultrices tincidunt arcu non sodales. Rutrum tellus pellentesque eu tincidunt. Placerat duis ultricies lacus sed turpis tincidunt id. Ultrices tincidunt arcu non sodales. Justo laoreet sit amet cursus sit amet dictum. Consectetur libero id faucibus nisl tincidunt. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque. Risus nec feugiat in fermentum posuere urna nec tincidunt. Eu sem integer vitae justo. Aliquam sem et tortor consequat id porta. Lacinia at quis risus sed vulputate odio ut enim. Amet mattis vulputate enim nulla aliquet porttitor lacus.\n" +
    "\n").split('\n')

